### ISSUE TITLE
샌드위치 주문 어플

### ISSUE THREAD

**Issue by ansoojeong** [cplkimth/kcci_iot_p1#9]
DB기반으로 샌드위치 주문 어플

1. 회원가입 후 로그인

2. 샌드위치 주문
-샌드위치 종류를 선택하면 세부 옵션(빵, 굽기, 소스, 채소 등)을 선택

3. 주문한 샌드위치를 DB에 저장
-주문 이력 확인 가능

**Comment by cplkimth** [comment]
너무 성의가 없다능.. 더 자세히 적어달라능,,
